app:
  no_default_user_group: true
  create_group_per_user: true
  add_user_to_domain_group: true
  code_editor_enabled: true
  default_redis_target: "localhost:6379"
  enable_target_tracking: true
database:
  data_source: "sqlite3:///tmp/buildbuddy-enterprise.db"
storage:
  ttl_seconds: 86400 # One day in seconds.
  disk:
    root_directory: /tmp/buildbuddy_enterprise
  enable_chunked_event_logs: true
cache:
  # Sample flow if migration disk -> pebble

  # Begin double writing, and still return data from disk
  disk:
    root_directory: /tmp/buildbuddy-enterprise-cache
    migration_src: true
  pebble:
    root_directory: /tmp/buildbuddy-enterprise-cache
    migration_dest: true

  # Copy all data from disk -> pebble
  disk:
    root_directory: /tmp/buildbuddy-enterprise-cache
    migration_src: true
  pebble:
    root_directory: /tmp/buildbuddy-enterprise-cache
    migration_dest: true
  migration_cache:
    migrate_and_exit: true

  # Double read for a period, fix any bugs, still use disk as source of truth
  disk:
    root_directory: /tmp/buildbuddy-enterprise-cache
    migration_src: true
  pebble:
    root_directory: /tmp/buildbuddy-enterprise-cache
    migration_dest: true
  migration_cache:
      double_read_percentage: 0.1

  # Once double reads are stable, keep double writing, but now return data from pebble
  disk:
    root_directory: /tmp/buildbuddy-enterprise-cache
    migration_dest: true
  pebble:
    root_directory: /tmp/buildbuddy-enterprise-cache
    migration_src: true

  # Something goes wrong with pebble - i.e. bug with write logic and we want to stop double writes
  # and clean up corrupted data in pebble
  disk:
    root_directory: /tmp/buildbuddy-enterprise-cache
  migration:
     clear_cache_before_migration: true

  # Fully confident with pebble, want to stop double writing to disk
  pebble:
    root_directory: /tmp/buildbuddy-enterprise-cache




auth:
  enable_anonymous_usage: true
  enable_self_auth: true
  # oauth_providers:
  #   - issuer_url: "https://accounts.google.com"
  #     client_id: "${BB_DEV_OAUTH_CLIENT_ID}"
  #     client_secret: "${BB_DEV_OAUTH_CLIENT_SECRET}"
github:
  client_id: "${BB_DEV_GITHUB_CLIENT_ID}"
  client_secret: "${BB_DEV_GITHUB_CLIENT_SECRET}"
