{
 "title": "BuildBuddy Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "region", "query": { "query": "label_values(up, region)" } },
   {
    "name": "window",
    "label": "Averaging Window",
    "query": "30s, 1m, 5m, 10m, 15m, 30m, 1h, 2h, 4h, 8h, 16h, 1d, 2d, 5d, 7d, 14d, 30d"
   },
   {
    "name": "job",
    "label": "Jobs",
    "query": {
     "query": "label_values(up{region=\"$region\"}, job)"
    }
   },
   {
    "name": "pool",
    "label": "Executor pool",
    "query": {
     "query": "label_values(up{region=\"$region\"}, job)"
    }
   },
   {
    "name": "kubepool",
    "query": {
     "query": "label_values(node_uname_info{region=\"$region\"}, nodename)"
    }
   },
   {
    "name": "kubenode",
    "query": {
     "query": "label_values(node_uname_info{region=\"$region\"}, nodename)"
    }
   },
   {
    "name": "quantile",
    "query": "0.25,0.5,0.75,0.9,0.95,0.99,0.999,0.9999"
   }
  ]
 },
 "panels": [
  {
   "title": "System status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "${job} instances",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "repeat": "job",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(up{region=\"${region}\", job=\"${job}\"})",
       "legendFormat": "Up"
      },
      {
       "expr": "sum(kube_pod_status_ready{region=\"${region}\", pod=~\"${job}-([0-9a-f]{8,10}-.*|[0-9]+)$\"})",
       "legendFormat": "Ready"
      }
     ]
    },
    {
     "title": "Unexpected Restarts",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kube_pod_container_status_restarts_total{region=\"${region}\"}[1m])) by (pod, container, exported_namespace) > 0"
      }
     ]
    }
   ]
  },
  {
   "title": "Probers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Success Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(cloudprober_success{region=\"${region}\"}[10m])) by (probe) / sum(increase(cloudprober_total{region=\"${region}\"}[10m])) by (probe)",
       "legendFormat": "{{probe}}"
      }
     ]
    },
    {
     "title": "RBE Prober Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.99,\n  sum by (le, stage)\n    (rate(buildbuddy_remote_execution_executed_action_metadata_durations_usec_bucket{region=\"${region}\", job=\"executor\", stage!=\"worker\", group_id=~\"GR16310856858823099217|GR13567963851860390298|GR11301939955034629488\"}[1m]))\n)\n\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Invocations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Invocations per second (by status)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (invocation_status) (rate(buildbuddy_invocation_count{region=\"${region}\"}[${window}]))",
       "legendFormat": "{{invocation_status}}"
      }
     ]
    },
    {
     "title": "Median invocation duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 9, "y": 3 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(buildbuddy_invocation_duration_usec_bucket{region=\"${region}\"}[${window}])) by (le))"
      }
     ]
    },
    {
     "title": "Invocations per second (by bazel exit code)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (bazel_exit_code) (rate(buildbuddy_invocation_count{region=\"${region}\"}[${window}]))",
       "legendFormat": "{{bazel_exit_code}}"
      }
     ]
    },
    {
     "title": "Build events uploaded per second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 9, "y": 11 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_invocation_build_event_count{region=\"${region}\"}[${window}]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Invocation finalizers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Stats recorder workers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "buildbuddy_invocation_stats_recorder_workers{region=\"${region}\"}"
      }
     ]
    },
    {
     "title": "Median stats recorder duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile(\n    0.5,\n    sum(rate(buildbuddy_invocation_stats_recorder_duration_usec_bucket{region=\"${region}\"}[${window}])) by (le)\n)"
      }
     ]
    },
    {
     "title": "Webhook invocation lookup workers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "buildbuddy_invocation_webhook_invocation_lookup_workers{region=\"${region}\"}"
      }
     ]
    },
    {
     "title": "Median webhook invocation lookup duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile(\n    0.5,\n    sum(rate(buildbuddy_invocation_webhook_invocation_lookup_duration_usec_bucket{region=\"${region}\"}[${window}])) by (le)\n)"
      }
     ]
    },
    {
     "title": "Webhook notification workers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "buildbuddy_invocation_webhook_notify_workers{region=\"${region}\"}"
      }
     ]
    },
    {
     "title": "Median webhook notify duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile(\n    0.5,\n    sum(rate(buildbuddy_invocation_webhook_notify_duration_usec_bucket{region=\"${region}\"}[${window}])) by (le)\n)"
      }
     ]
    }
   ]
  },
  {
   "title": "Workflows",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Workflows started",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_webhook_handler_workflows_started{region=\"${region}\"}[${window}]))"
      }
     ]
    },
    {
     "title": "Workflows started by trigger event",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (event) (rate(buildbuddy_webhook_handler_workflows_started{region=\"${region}\", event!=\"\"}[${window}]))",
       "legendFormat": "{{event}}"
      },
      {
       "expr": "sum (rate(buildbuddy_webhook_handler_workflows_started{region=\"${region}\", event=\"\"}[${window}]))",
       "legendFormat": "rerun_button"
      }
     ]
    },
    {
     "title": "Webhook events by response code",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (code) (rate(buildbuddy_http_request_handler_duration_usec_count{region=\"${region}\",route=\"/webhooks/workflow/:id\"}[${window}]))",
       "legendFormat": "{{code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Distributed Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Mix",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_started_total{region=\"${region}\",grpc_service=\"distributed_cache.DistributedCache\"}[${window}])) by (grpc_method)\n",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "/GetMulti",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(grpc_server_handling_seconds_bucket{region=\"${region}\", grpc_service=\"distributed_cache.DistributedCache\", grpc_method=\"GetMulti\"}[${window}])) by (le)\n)",
       "legendFormat": "P99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(grpc_server_handling_seconds_bucket{region=\"${region}\", grpc_service=\"distributed_cache.DistributedCache\", grpc_method=\"GetMulti\"}[${window}])) by (le)\n)",
       "legendFormat": "P95"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(grpc_server_handling_seconds_bucket{region=\"${region}\", grpc_service=\"distributed_cache.DistributedCache\", grpc_method=\"GetMulti\"}[${window}])) by (le)\n)",
       "legendFormat": "P50"
      },
      {
       "expr": "sum(rate(grpc_server_handled_total{region=\"${region}\", grpc_service=\"distributed_cache.DistributedCache\", grpc_method=\"GetMulti\"}[${window}])) by (grpc_service)",
       "legendFormat": "QPS"
      }
     ]
    },
    {
     "title": "/FindMissing",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(grpc_server_handling_seconds_bucket{region=\"${region}\", grpc_service=\"distributed_cache.DistributedCache\", grpc_method=\"FindMissing\"}[${window}])) by (le)\n)",
       "legendFormat": "P99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(grpc_server_handling_seconds_bucket{region=\"${region}\", grpc_service=\"distributed_cache.DistributedCache\", grpc_method=\"FindMissing\"}[${window}])) by (le)\n)",
       "legendFormat": "P95"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(grpc_server_handling_seconds_bucket{region=\"${region}\", grpc_service=\"distributed_cache.DistributedCache\", grpc_method=\"FindMissing\"}[${window}])) by (le)\n)",
       "legendFormat": "P50"
      },
      {
       "expr": "sum(rate(grpc_server_handled_total{region=\"${region}\", grpc_service=\"distributed_cache.DistributedCache\", grpc_method=\"FindMissing\"}[${window}])) by (grpc_service)",
       "legendFormat": "QPS"
      }
     ]
    },
    {
     "title": "/Write",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(grpc_server_handling_seconds_bucket{region=\"${region}\", grpc_service=\"distributed_cache.DistributedCache\", grpc_method=\"Write\"}[${window}])) by (le)\n)",
       "legendFormat": "P99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(grpc_server_handling_seconds_bucket{region=\"${region}\", grpc_service=\"distributed_cache.DistributedCache\", grpc_method=\"Write\"}[${window}])) by (le)\n)",
       "legendFormat": "P95"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(grpc_server_handling_seconds_bucket{region=\"${region}\", grpc_service=\"distributed_cache.DistributedCache\", grpc_method=\"Write\"}[${window}])) by (le)\n)",
       "legendFormat": "P50"
      },
      {
       "expr": "sum(rate(grpc_server_handled_total{region=\"${region}\", grpc_service=\"distributed_cache.DistributedCache\", grpc_method=\"Write\"}[${window}])) by (grpc_service)",
       "legendFormat": "QPS"
      }
     ]
    },
    {
     "title": "/Read",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(grpc_server_handling_seconds_bucket{region=\"${region}\", grpc_service=\"distributed_cache.DistributedCache\", grpc_method=\"Read\"}[${window}])) by (le)\n)",
       "legendFormat": "P99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(grpc_server_handling_seconds_bucket{region=\"${region}\", grpc_service=\"distributed_cache.DistributedCache\", grpc_method=\"Read\"}[${window}])) by (le)\n)",
       "legendFormat": "P95"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(grpc_server_handling_seconds_bucket{region=\"${region}\", grpc_service=\"distributed_cache.DistributedCache\", grpc_method=\"Read\"}[${window}])) by (le)\n)",
       "legendFormat": "P50"
      },
      {
       "expr": "sum(rate(grpc_server_handled_total{region=\"${region}\", grpc_service=\"distributed_cache.DistributedCache\", grpc_method=\"Read\"}[${window}])) by (grpc_service)",
       "legendFormat": "QPS"
      }
     ]
    }
   ]
  },
  {
   "title": "Remote cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total downloaded bytes per second",
     "type": "graph",
     "description": "Total number of bytes downloaded by consumers of the cache, per second. This does _not_ represent the average download speed across cache requests.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_remote_cache_download_size_bytes_sum{region=\"${region}\"}[${window}]))"
      }
     ]
    },
    {
     "title": "Total uploaded bytes per second",
     "type": "graph",
     "description": "Total number of bytes uploaded by consumers of the cache, per second. This does _not_ represent the average upload speed across cache requests.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_remote_cache_upload_size_bytes_sum{region=\"${region}\"}[${window}]))"
      }
     ]
    },
    {
     "title": "Action cache events per second",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
     "repeat": "cache_type",
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (cache_event_type) (rate(buildbuddy_remote_cache_events{region=\"${region}\", cache_type=\"action_cache\"}[${window}]))",
       "legendFormat": "{{cache_event_type}}"
      }
     ]
    },
    {
     "title": "CAS events per second",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (cache_event_type) (rate(buildbuddy_remote_cache_events{region=\"${region}\", cache_type=\"cas\"}[${window}]))",
       "legendFormat": "{{cache_event_type}}"
      }
     ]
    },
    {
     "title": "Disk Cache Avg Last Evicted Age",
     "type": "graph",
     "description": "Avg age of last item evicted by the disk cache",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(buildbuddy_remote_cache_disk_cache_last_eviction_age_usec{region=\"${region}\"}/1e6) by (partition_id)"
      }
     ]
    },
    {
     "title": "Disk Cache Duplicate Writes per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_remote_cache_disk_cache_duplicate_writes{}[${window}]))"
      }
     ]
    },
    {
     "title": "Files Added to Disk Cache by Size",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "sum(increase(buildbuddy_remote_cache_disk_cache_added_file_size_bytes_bucket[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Disk Cache by Time Since Last Access",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "targets": [
      {
       "expr": "sum(increase(buildbuddy_remote_cache_disk_cache_usec_since_last_access_bucket[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Remote execution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Execution Request Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_remote_execution_requests{region=\"${region}\"}[5m])) by (group_id, os, arch)"
      }
     ]
    },
    {
     "title": "Num Execution Result Waiters (Sum Across Apps)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(buildbuddy_remote_execution_waiting_execution_result{region=\"${region}\"}) by (group_id)",
       "legendFormat": "{{group_id}}"
      }
     ]
    },
    {
     "title": "Num Execution Result Waiters (Max Across Apps)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(sum(buildbuddy_remote_execution_waiting_execution_result{region=\"${region}\"}) by (pod_name,group_id)) by (group_id)",
       "legendFormat": "{{group_id}}"
      }
     ]
    },
    {
     "title": "Task sizer reads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (status) (rate(buildbuddy_remote_execution_task_size_read_requests{region=\"${region}\"}[${window}]))",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Task sizer writes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (status) (rate(buildbuddy_remote_execution_task_size_write_requests{region=\"${region}\"}[${window}]))",
       "legendFormat": "{{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Executor pool (${pool})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "repeat": "pool",
   "collapsed": true,
   "panels": [
    {
     "title": "Fraction of working executors",
     "type": "graph",
     "description": "Chart is stacked, so values always add up to 100%.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "count(sum by (pod_name) (buildbuddy_remote_execution_tasks_executing{region=\"${region}\", job=\"${pool}\"}) > 0) / count(sum by (pod_name) (buildbuddy_remote_execution_tasks_executing{region=\"${region}\", job=\"${pool}\"}))",
       "legendFormat": "Working"
      },
      {
       "expr": "1 - count(sum by (pod_name) (buildbuddy_remote_execution_tasks_executing{region=\"${region}\", job=\"${pool}\"}) > 0) / count(sum by (pod_name) (buildbuddy_remote_execution_tasks_executing{region=\"${region}\", job=\"${pool}\"}))",
       "legendFormat": "Idle"
      }
     ]
    },
    {
     "title": "Executor autoscaling",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(sum by (pod_name) (buildbuddy_remote_execution_queue_length{region=\"${region}\", job=\"${pool}\"}))",
       "legendFormat": "Avg executor queue length"
      },
      {
       "expr": "sum(up{region=\"${region}\", job=\"${pool}\"})",
       "legendFormat": "Executor instances"
      },
      {
       "expr": "kube_horizontalpodautoscaler_status_desired_replicas{region=\"${region}\", horizontalpodautoscaler=\"${pool}-autoscaler\"}",
       "legendFormat": "Autoscaler target"
      }
     ]
    },
    {
     "title": "Action stage durations (quantile=${quantile})",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  ${quantile},\n  sum by (le, stage) (rate(buildbuddy_remote_execution_executed_action_metadata_durations_usec_bucket{region=\"${region}\", stage!=\"worker\", job=\"${pool}\"}[${window}]))\n)",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "Tasks executing by stage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "sum by (stage) (buildbuddy_remote_execution_tasks_executing{region=\"${region}\", job=\"${pool}\"})",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "Actions executed per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by (status) (rate(buildbuddy_remote_execution_count{region=\"${region}\", job=\"${pool}\"}[${window}]))",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Avg resources allocated to tasks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(buildbuddy_remote_execution_assigned_milli_cpu{region=\"${region}\", job=\"${pool}\"}\n  / on (pod_name) (\n  label_replace(kube_pod_container_resource_limits_cpu_cores{region=\"${region}\", pod=~\"${pool}-.*\"} * 1000, \"pod_name\", \"$1\", \"pod\", \"(.*)\")))",
       "legendFormat": "Avg CPU assigned"
      },
      {
       "expr": "avg(buildbuddy_remote_execution_assigned_ram_bytes{region=\"${region}\", job=\"${pool}\"}\n  / on (pod_name) (\n  label_replace(kube_pod_container_resource_limits_memory_bytes{region=\"${region}\", pod=~\"${pool}-.*\"}, \"pod_name\", \"$1\", \"pod\", \"(.*)\")))",
       "legendFormat": "Avg RAM assigned"
      }
     ]
    },
    {
     "title": "Task memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(buildbuddy_remote_execution_memory_usage_bytes{region=\"${region}\", job=\"${pool}\"})",
       "legendFormat": "Current memory usage"
      },
      {
       "expr": "sum(buildbuddy_remote_execution_peak_memory_usage_bytes{region=\"${region}\", job=\"${pool}\"})",
       "legendFormat": "Current peak memory usage"
      },
      {
       "expr": "sum(buildbuddy_remote_execution_assigned_ram_bytes{region=\"${region}\", job=\"${pool}\"})",
       "legendFormat": "Estimated memory usage"
      },
      {
       "expr": "sum(buildbuddy_remote_execution_assignable_ram_bytes{region=\"${region}\", job=\"${pool}\"})",
       "legendFormat": "Max assignable memory"
      }
     ]
    },
    {
     "title": "Task CPU usage (each 100% = 1 fully utilized core)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(buildbuddy_remote_execution_cpu_utilization_milli_cpu{region=\"${region}\",job=\"${pool}\"})/1000",
       "legendFormat": "CPU (current, 1s avg)"
      },
      {
       "expr": "sum(rate(buildbuddy_remote_execution_used_milli_cpu{region=\"${region}\",job=\"${pool}\"}[${window}]))/1000",
       "legendFormat": "CPU (smoothed, ${window} rate)"
      },
      {
       "expr": "sum(buildbuddy_remote_execution_assigned_milli_cpu{region=\"${region}\",job=\"${pool}\"})/1000",
       "legendFormat": "Estimated CPU"
      },
      {
       "expr": "sum(buildbuddy_remote_execution_assignable_milli_cpu{region=\"${region}\",job=\"${pool}\"})/1000",
       "legendFormat": "Max assignable CPU"
      }
     ]
    },
    {
     "title": "Total downloaded bytes per second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_remote_execution_file_download_size_bytes_sum{region=\"${region}\", job=\"${pool}\"}[${window}]))"
      }
     ]
    },
    {
     "title": "Total uploaded bytes per second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_remote_execution_file_upload_size_bytes_sum{region=\"${region}\", job=\"${pool}\"}[${window}]))"
      }
     ]
    },
    {
     "title": "Median executor queue length",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "quantile(0.5, sum by (pod_name) (buildbuddy_remote_execution_queue_length{region=\"${region}\", job=\"${pool}\"}))"
      }
     ]
    },
    {
     "title": "Executor queue length by pod",
     "type": "graph",
     "description": "Number of actions waiting to be executed",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (pod_name) (buildbuddy_remote_execution_queue_length{region=\"${region}\", job=\"${pool}\"})",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "File cache hit rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_remote_execution_file_cache_requests{status=\"hit\", region=\"${region}\", job=\"${pool}\"}[${window}]))\n  /\nsum(rate(buildbuddy_remote_execution_file_cache_requests{region=\"${region}\", job=\"${pool}\"}[${window}]))",
       "legendFormat": "Hit rate"
      }
     ]
    },
    {
     "title": "Total CPU usage (CPU seconds)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{region=\"${region}\", pod=~\"${pool}-[a-f0-9].*\"}[5m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "File cache added file size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.5,\n  sum by (le) (rate(buildbuddy_remote_execution_file_cache_added_file_size_bytes_bucket{region=\"${region}\", job=\"${pool}\"}[${window}]))\n)",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(\n  0.9,\n  sum by (le) (rate(buildbuddy_remote_execution_file_cache_added_file_size_bytes_bucket{region=\"${region}\", job=\"${pool}\"}[${window}]))\n)",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(\n  0.99,\n  sum by (le) (rate(buildbuddy_remote_execution_file_cache_added_file_size_bytes_bucket{region=\"${region}\", job=\"${pool}\"}[${window}]))\n)",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(\n  0.9999,\n  sum by (le) (rate(buildbuddy_remote_execution_file_cache_added_file_size_bytes_bucket{region=\"${region}\", job=\"${pool}\"}[${window}]))\n)",
       "legendFormat": "p99.99"
      }
     ]
    },
    {
     "title": "File cache last eviction age",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "buildbuddy_remote_execution_file_cache_last_eviction_age_usec{region=\"${region}\", job=\"${pool}\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Runner recycling (${pool})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "repeat": "pool",
   "collapsed": true,
   "panels": [
    {
     "title": "Pooled runner count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(buildbuddy_remote_execution_runner_pool_count{region=\"${region}\", job=\"${pool}\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "avg(buildbuddy_remote_execution_runner_pool_count{region=\"${region}\", job=\"${pool}\"})",
       "legendFormat": "Average"
      },
      {
       "expr": "sum(up{region=\"${region}\", job=\"${pool}\"})",
       "legendFormat": "Executor count (for comparison)"
      }
     ]
    },
    {
     "title": "Runner pool evictions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_remote_execution_runner_pool_evictions{region=\"${region}\", job=\"${pool}\"}[${window}]))"
      }
     ]
    },
    {
     "title": "Recycling failures by reason",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (reason) (rate(buildbuddy_remote_execution_runner_pool_failed_recycle_attempts{region=\"${region}\", job=\"${pool}\"}[${window}]))",
       "legendFormat": "{{reason}}"
      }
     ]
    },
    {
     "title": "Pool requests by status",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (status) (rate(buildbuddy_remote_execution_recycle_runner_requests{region=\"${region}\", job=\"${pool}\"}[${window}]))",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Total memory usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(buildbuddy_remote_execution_runner_pool_memory_usage_bytes{region=\"${region}\", job=\"${pool}\"})"
      }
     ]
    },
    {
     "title": "Total workspace size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(buildbuddy_remote_execution_runner_pool_disk_usage_bytes{region=\"${region}\", job=\"${pool}\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "SQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQL queries per second (by query template)",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (sql_query_template) (rate(buildbuddy_sql_query_count{region=\"${region}\"}[${window}]))",
       "legendFormat": "{{sql_query_template}}"
      }
     ]
    },
    {
     "title": "Median SQL query duration by query template",
     "type": "graph",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.5,\n  sum by (sql_query_template, le) (rate(buildbuddy_sql_query_duration_usec_bucket{region=\"${region}\"}[${window}]))\n)",
       "legendFormat": "{{sql_query_template}}"
      }
     ]
    },
    {
     "title": "SQL queries per second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_sql_query_count{region=\"${region}\"}[${window}]))"
      }
     ]
    },
    {
     "title": "SQL error rate (errors per second / queries per second)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_sql_error_count{region=\"${region}\"}[${window}]))\n/ (sum(rate(buildbuddy_sql_query_count{region=\"${region}\"}[${window}])))"
      }
     ]
    },
    {
     "title": "SQL errors per second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_sql_error_count{region=\"${region}\"}[${window}]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Redis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "redis_memory_used_bytes{region=\"${region}\"} / redis_memory_max_bytes{region=\"${region}\"}",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Total items per DB",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (redis_db_keys{region=\"${region}\"}) by (db)",
       "legendFormat": "{{db}}"
      }
     ]
    },
    {
     "title": "Total number of clients",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redis_connected_clients{region=\"${region}\"})"
      }
     ]
    },
    {
     "title": "Total commands per second",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(redis_commands_total{region=\"${region}\"}[${window}])) by (cmd)",
       "legendFormat": "{{ cmd }}"
      }
     ]
    },
    {
     "title": "Average time spent by command per second",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(irate(redis_commands_duration_seconds_total{region=\"${region}\"}[${window}])) by (cmd)\n  /\nsum(irate(redis_commands_total{region=\"${region}\"}[${window}])) by (cmd)\n",
       "legendFormat": "{{ cmd }}"
      }
     ]
    },
    {
     "title": "Total Time Spent by Command / sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(irate(redis_commands_duration_seconds_total{region=\"${region}\"}[${window}])) by (cmd) != 0",
       "legendFormat": "{{ cmd }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Blobstore",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Downloaded bytes per second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_blobstore_read_size_bytes_sum{region=\"${region}\"}[${window}]))"
      }
     ]
    },
    {
     "title": "Median download duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(buildbuddy_blobstore_read_duration_usec_bucket{region=\"${region}\"}[${window}])) by (le))"
      }
     ]
    },
    {
     "title": "Uploaded bytes per second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_blobstore_write_size_bytes_sum{region=\"${region}\"}[${window}]))"
      }
     ]
    },
    {
     "title": "Median upload duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(buildbuddy_blobstore_write_duration_usec_bucket{region=\"${region}\"}[${window}])) by (le))"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP 5xx error ratio",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_http_request_handler_duration_usec_count{region=\"${region}\", code=~\"5..\"}[${window}]))\n  /\nsum(rate(buildbuddy_http_request_handler_duration_usec_count{region=\"${region}\"}[${window}]))",
       "legendFormat": "Error ratio"
      }
     ]
    },
    {
     "title": "HTTP requests per second by route",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (route) (rate(buildbuddy_http_request_count{region=\"${region}\"}[${window}]))",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "HTTP requests per second by method",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (method) (rate(buildbuddy_http_request_count{region=\"${region}\"}[${window}]))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "HTTP responses per second by status",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (code) (rate(buildbuddy_http_request_handler_duration_usec_count{region=\"${region}\"}[${window}]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Median HTTP request handler duration (2xx responses only)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 127 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.5,\n  sum by (le, code) (rate(buildbuddy_http_request_handler_duration_usec_bucket{region=\"${region}\", code=~\"2..\"}[${window}])))"
      }
     ]
    },
    {
     "title": "Median HTTP response size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 127 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.5,\n  sum by (le) (rate(buildbuddy_http_response_size_bytes_bucket{region=\"${region}\"}[${window}]))\n)"
      }
     ]
    }
   ]
  },
  {
   "title": "golang (${job})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "repeat": "job",
   "collapsed": true,
   "panels": [
    {
     "title": "Heap size",
     "type": "graph",
     "description": "Number of heap bytes allocated and still in use.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{region=\"${region}\", job=\"${job}\"}",
       "legendFormat": "{{job}} @ {{pod_name}}"
      },
      {}
     ]
    },
    {
     "title": "goroutines",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{region=\"${region}\", job=\"${job}\"}",
       "legendFormat": "{{job}} @ {{pod_name}}"
      }
     ]
    },
    {
     "title": "GC CPU fraction",
     "type": "graph",
     "description": "% of time spent in the garbage collector since the program started.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "go_memstats_gc_cpu_fraction{region=\"${region}\", job=\"${job}\"}",
       "legendFormat": "{{job}} @ {{pod_name}}"
      }
     ]
    },
    {
     "title": "Median GC duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{region=\"${region}\", quantile=\"0.5\",job=\"${job}\"}",
       "legendFormat": "{{job}} @ {{pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC (buildbuddy-app)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Handled gRPC requests per second by status",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (grpc_code) (rate(grpc_server_handled_total{region=\"${region}\", job=\"buildbuddy-app\"}[${window}]))",
       "legendFormat": "{{grpc_code}}"
      }
     ]
    },
    {
     "title": "Handled gRPC requests per second by method",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (grpc_service, grpc_method) (rate(grpc_server_handled_total{region=\"${region}\", job=\"buildbuddy-app\"}[${window}]))",
       "legendFormat": "/{{grpc_service}}/{{grpc_method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kubernetes Nodes Overview (${kubepool})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "repeat": "kubepool",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1 - (avg by(mode,nodename) ((rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * on(instance) group_left(nodename) (node_uname_info{region=\"${region}\", nodename=~\"^${kubepool}-([0-9a-f]{8})-[0-9a-z]{4}$\"})))",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "Disk",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "max by (nodename) (rate(node_disk_read_bytes_total[1m]) * on(instance) group_left(nodename) (node_uname_info{region=\"${region}\", nodename=~\"^${kubepool}-([0-9a-f]{8})-[0-9a-z]{4}$\"}))",
       "legendFormat": "reads {{nodename}}"
      },
      {
       "expr": "max by (nodename) (rate(node_disk_written_bytes_total[1m]) * on(instance) group_left(nodename) (node_uname_info{region=\"${region}\", nodename=~\"^${kubepool}-([0-9a-f]{8})-[0-9a-z]{4}$\"}))\n",
       "legendFormat": "writes {{nodename}}"
      }
     ]
    },
    {
     "title": "Network",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{device=~\"ens.*\"}[1m]) * on(instance) group_left(nodename) (node_uname_info{region=\"${region}\", nodename=~\"^${kubepool}-([0-9a-f]{8})-[0-9a-z]{4}$\"})\n",
       "legendFormat": "rx {{nodename}}"
      },
      {
       "expr": "rate(node_network_transmit_bytes_total{device=~\"ens.*\"}[1m]) * on(instance) group_left(nodename) (node_uname_info{region=\"${region}\", nodename=~\"^${kubepool}-([0-9a-f]{8})-[0-9a-z]{4}$\"})\n",
       "legendFormat": "tx {{nodename}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kubernetes Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "${kubenode} disk and network IO",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "repeat": "kubenode",
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(node_disk_read_bytes_total[1m]) * on(instance) group_left(nodename) (node_uname_info{region=\"${region}\", nodename=\"${kubenode}\"})",
       "legendFormat": "{{device}} reads"
      },
      {
       "expr": "rate(node_disk_written_bytes_total[1m]) * on(instance) group_left(nodename) (node_uname_info{region=\"${region}\", nodename=\"${kubenode}\"})",
       "legendFormat": "{{device}} writes"
      },
      {
       "expr": "rate(node_network_receive_bytes_total{device=~\"ens.*\"}[1m]) * on(instance) group_left(nodename) (node_uname_info{region=\"${region}\", nodename=\"${kubenode}\"})",
       "legendFormat": "{{device}} rx"
      },
      {
       "expr": "rate(node_network_transmit_bytes_total{device=~\"ens.*\"}[1m]) * on(instance) group_left(nodename) (node_uname_info{region=\"${region}\", nodename=\"${kubenode}\"})",
       "legendFormat": "{{device}} tx"
      },
      {
       "expr": "1 - (avg by(mode) ((rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * on(instance) group_left(nodename) (node_uname_info{region=\"${region}\", nodename=\"${kubenode}\"})))",
       "legendFormat": "cpu"
      }
     ]
    },
    {
     "title": "${kubenode} memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "repeat": "kubenode",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_active_bytes * on(instance) group_left(nodename) (node_uname_info{region=\"${region}\", nodename=\"${kubenode}\"})",
       "legendFormat": "Active memory"
      },
      {
       "expr": "node_memory_compressed_bytes * on(instance) group_left(nodename) (node_uname_info{region=\"${region}\", nodename=\"${kubenode}\"})",
       "legendFormat": "Compressed memory"
      },
      {
       "expr": "node_memory_wired_bytes * on(instance) group_left(nodename) (node_uname_info{region=\"${region}\", nodename=\"${kubenode}\"})",
       "legendFormat": "Wired memory"
      },
      {
       "expr": "node_memory_inactive_bytes * on(instance) group_left(nodename) (node_uname_info{region=\"${region}\", nodename=\"${kubenode}\"})",
       "legendFormat": "Inactive memory"
      },
      {
       "expr": "node_memory_free_bytes * on(instance) group_left(nodename) (node_uname_info{region=\"${region}\", nodename=\"${kubenode}\"})",
       "legendFormat": "Free memory"
      }
     ]
    }
   ]
  },
  {
   "title": "Internal",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Build event handler duration",
     "type": "graph",
     "description": "Measures the time spent handling build events. In a healthy state, this should be very small (on the order of microseconds) in most cases, since the build event handler needs to be very high throughput.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(buildbuddy_build_event_handler_duration_usec_bucket{region=\"${region}\"}[${window}])) by (le))",
       "legendFormat": "Median"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(buildbuddy_build_event_handler_duration_usec_bucket{region=\"${region}\"}[${window}])) by (le))",
       "legendFormat": "90th %"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(buildbuddy_build_event_handler_duration_usec_bucket{region=\"${region}\"}[${window}])) by (le))",
       "legendFormat": "95th %"
      }
     ]
    },
    {
     "title": "Unexpected events",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (name) (rate(buildbuddy_unexpected_event{region=\"${region}\"}[${window}]))"
      }
     ]
    },
    {
     "title": "RPCs by Quota Key",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "sum by (grpc_full_method, quota_key) (rate(buildbuddy_quota_rpcs_handled_total_by_quota_key{region=\"${region}\"}[${window}]))"
      }
     ]
    }
   ]
  }
 ]
}